### PR TITLE
Fix empty conf handling

### PR DESCRIPTION
**Pull request by david-caro**

### CODE REVIEW

**Comment by david-caro** [comment]
@lnielsen can you review? (I have no right to add labels/reviewers...)

**Comment by lnielsen** [comment]
👍 

I've fixed the permissions now. Can you check if you can merge this one?

**Comment by david-caro** [comment]
Yep, now I see the 'merge' button and can add/change labes, asignees and reviewers 🎉

**Comment by david-caro** [comment]
Should I squash it? (seems to be the default merge strategy)

**Comment by lnielsen** [comment]
If there's more than one commit I usually use the rebase button or merge manually.....

**Comment by david-caro** [comment]
Is it an issue if I create merge commits?


--
David Caro <david.caro@cern.ch>

CERN - RCS-SIS
inSPIRE-HEP High Energy Physics information system
http://inspirehep.net
On May 8, 2017 10:05 PM, Lars Holm Nielsen <notifications@github.com> wrote:

If there's more than one commit I usually use the rebase button or merge manually.....

**Comment by lnielsen** [comment]
I'd prefer we stick to the same all over inveniosoftware which so far is not to have merge commits.

**Comment by david-caro** [comment]
Ok, just curious, what was the reason for not having merge commits?


--
David Caro <david.caro@cern.ch>

CERN - RCS-SIS
inSPIRE-HEP High Energy Physics information system
http://inspirehep.net
On May 9, 2017 7:46 AM, Lars Holm Nielsen <notifications@github.com> wrote:

I'd prefer we stick to the same all over inveniosoftware which so far is not to have merge commits.

**Comment by lnielsen** [comment]
The practice goes back to before I started at CERN and I believe the reason is to have clean commit history (i.e. new commits are always on the top of the commit log). Naturally you could have something similar with merge commits if the branch is always up-to-date before merging.

**Comment by david-caro** [comment]
I don't really see how would you not have that with git... but ok, maybe we can discuss it at some point.

**Comment by lnielsen** [comment]
With the merge commit, only the merge commit will end up on the top. The other commits will be sorted according to commit date AFAIK. 

I'm fine allow merge commits if there's consensus among developers that this is the way to go. For me it's just important that we apply consistent rules on all repos.

**Comment by david-caro** [comment]
That depends on how you sort them yep, :), but hierarchically, they are still ordered, and the main history branch (the one with the first parents, see `git log --first-parents`) will be quite similar, being the merge commit the 'squashed' one, but allowing you to see the contents of each individual commit on the merged branch if need be, for debugging, diffing, etc.

**Pull request merged**
